Repository WildCodeSchool/orleans-0918-php-loipinel, pull requests merged in 2018-11, with the labels that each got.

#1 Add codesniffer
  .travis.yml
  composer.json
  composer.lock
  symfony.lock
Labels: Reviewed by PO

#2 Webpack install
  .env
  .gitignore
  assets/.gitignore
  assets/css/app.scss
  assets/js/app.js
  composer.json
  composer.lock
  config/bundles.php
  config/packages/assets.yaml
  config/packages/webpack_encore.yaml
  package.json
  symfony.lock
  templates/base.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
  webpack.config.js
  yarn.lock
Labels: conflict

#9 Dev to Master
  .env
  .gitignore
  assets/.gitignore
  assets/css/app.scss
  assets/js/app.js
  composer.json
  composer.lock
  config/bundles.php
  config/packages/assets.yaml
  config/packages/webpack_encore.yaml
  package.json
  symfony.lock
  templates/base.html.twig
  templates/layout.html.twig
  templates/layoutAdmin.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed by PO

#17 S2 navbar projet io
  .travis.yml
  assets/css/app.scss
  assets/fonts/BrandonGrotesque-Bold.otf
  assets/fonts/BrandonGrotesque-BoldItalic.otf
  assets/fonts/BrandonGrotesque-Regular.otf
  assets/fonts/BrandonGrotesque-RegularItalic.otf
  assets/fonts/BrandonText-Bold.otf
  assets/fonts/BrandonText-BoldItalic.otf
  assets/fonts/BrandonText-Regular.otf
  assets/fonts/BrandonText-RegularItalic.otf
  assets/js/app.js
  package.json
  templates/base.html.twig
  templates/layout.html.twig
  templates/navbarProjetIO.html.twig
  webpack.config.js
  yarn.lock
Labels: Reviewed by PO

#24 Sprint1 us 5 formulaire5
  assets/css/app.scss
  src/Controller/SimulatorController.php
  src/Entity/Simulator.php
  src/Form/SimulatorType.php
  templates/Form/simulator.html.twig
Labels: changes requested

#25 rewriting navbar
  assets/css/app.scss
  templates/navbarProjetIO.html.twig
Labels: Reviewed by PO

#27 fix navbar
  assets/css/app.scss
  templates/Form/simulator.html.twig
Labels: Reviewed by PO

#30 Fix fonts
  assets/css/app.scss
  templates/navbarProjetIO.html.twig
Labels: Reviewed by PO

#32 S1 us6 result page
  assets/css/app.scss
  src/Controller/ResultPageController.php
  src/Controller/SimulatorController.php
  templates/Form/simulator.html.twig
  templates/navbarProjetIO.html.twig
  templates/result.html.twig
Labels: Correction done, Reviewed by PO

#31 Sprint2 us11
  assets/js/apiAdressRequest.js
  src/Form/SimulatorType.php
  templates/Form/simulator.html.twig
  webpack.config.js
Labels: Correction done, Reviewed by PO

#33 Fix simulator
  assets/css/app.scss
  src/Entity/Simulator.php
  src/Form/SimulatorType.php
  templates/Form/simulator.html.twig
Labels: Reviewed by PO

#36 Passage du formulaire à la page de résultat.
  src/Form/SimulatorType.php
  templates/result.html.twig
Labels: Reviewed by PO

#37 Us01 navbar2
  assets/css/app.scss
  templates/layout.html.twig
  templates/navbarApplication.html.twig
Labels: Reviewed by PO

#38 Dev
  assets/css/app.scss
  assets/js/apiAdressRequest.js
  src/Controller/ResultPageController.php
  src/Controller/SimulatorController.php
  src/Entity/Simulator.php
  src/Form/SimulatorType.php
  templates/Form/simulator.html.twig
  templates/layout.html.twig
  templates/navbarApplication.html.twig
  templates/navbarProjetIO.html.twig
  templates/result.html.twig
  webpack.config.js
Labels: Reviewed by PO

#35 js modif
  assets/js/apiAdressRequest.js
Labels: Correction done, Reviewed by PO

#39 Adress field in result page
  templates/result.html.twig
Labels: Reviewed by PO
