Repository WildCodeSchool/orleans-0918-php-loipinel, pull requests merged in 2018-12, with the labels that each got.

#40 Dev
  assets/js/apiAdressRequest.js
  templates/result.html.twig
Labels: Reviewed by PO

#52 Us17 pdf
  .env
  assets/css/app.scss
  bin/wkhtml2pdf
  bin/wkhtmltopdf
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp_snappy.yaml
  src/Controller/ResultPageController.php
  symfony.lock
  templates/layoutPdf.html.twig
  templates/result.html.twig
  templates/resultTable.html.twig
  templates/resume.html.twig
Labels: Correction done, Reviewed by PO

#51 US7_PAGE_CONNEXION
  .travis.yml
  assets/css/app.scss
  composer.json
  composer.lock
  config/bundles.php
  config/packages/security.yaml
  config/routes.yaml
  src/Controller/ResultPageController.php
  src/Controller/SecurityController.php
  src/Controller/SimulatorController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Migrations/Version20181204084713.php
  src/Migrations/Version20181205104927.php
  src/Repository/UserRepository.php
  src/Security/AppAuthenticator.php
  symfony.lock
  templates/navbarProjetIO.html.twig
  templates/security/login.html.twig
Labels: Correction done, Reviewed by PO

#53 Dev
  .env
  .travis.yml
  assets/css/app.scss
  bin/wkhtml2pdf
  bin/wkhtmltopdf
  composer.json
  composer.lock
  config/bundles.php
  config/packages/knp_snappy.yaml
  config/packages/security.yaml
  config/routes.yaml
  src/Controller/ResultPageController.php
  src/Controller/SecurityController.php
  src/Controller/SimulatorController.php
  src/DataFixtures/UserFixtures.php
  src/Entity/User.php
  src/Migrations/Version20181204084713.php
  src/Migrations/Version20181205104927.php
  src/Repository/UserRepository.php
  src/Security/AppAuthenticator.php
  symfony.lock
  templates/layoutPdf.html.twig
  templates/navbarProjetIO.html.twig
  templates/result.html.twig
  templates/resultTable.html.twig
  templates/resume.html.twig
  templates/security/login.html.twig
Labels: Reviewed by PO

#55 Date picker update for chrome
  assets/css/app.scss
Labels: Reviewed by PO

#48 Us 16 algo for result
  src/Controller/ResultPageController.php
  src/Entity/RealEstateProperty.php
  src/Entity/Simulator.php
  src/Form/SimulatorType.php
  src/Service/TaxBenefit.php
  templates/result.html.twig
  templates/resultTable.html.twig
  tests/TaxBaseTest.php
Labels: Correction done, Reviewed by PO, conflict resolved

#56 Fix dev
  src/Controller/ResultPageController.php
  templates/resultTable.html.twig
Labels: Reviewed by PO

#57 Dev
  assets/css/app.scss
  src/Controller/ResultPageController.php
  src/Entity/RealEstateProperty.php
  src/Entity/Simulator.php
  src/Form/SimulatorType.php
  src/Service/TaxBenefit.php
  templates/result.html.twig
  templates/resultTable.html.twig
  tests/TaxBaseTest.php
Labels: Reviewed by PO

#64 fix Projet IO link redirect now to simulator page
  templates/navbarProjetIO.html.twig
Labels: Reviewed by PO

#65 US1_PANNEAU_ADMINISTRATEUR
  assets/css/app.scss
  src/Controller/UserController.php
  src/Form/UserType.php
  templates/layoutAdmin.html.twig
  templates/navbarApplication.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: Reviewed by PO

#69 Us10 avantage fiscal
  src/Controller/ResultPageController.php
  src/Service/TaxBenefit.php
  templates/resultTable.html.twig
  tests/TaxBaseTest.php
Labels: Correction done

#71 Dev
  assets/css/app.scss
  src/Controller/ResultPageController.php
  src/Controller/UserController.php
  src/Form/UserType.php
  src/Service/TaxBenefit.php
  templates/layoutAdmin.html.twig
  templates/navbarApplication.html.twig
  templates/navbarProjetIO.html.twig
  templates/resultTable.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
  tests/TaxBaseTest.php
Labels: Reviewed by PO

#79 Deleteuser
  src/DataFixtures/UserFixtures.php
  templates/user/_delete_form.html.twig
  templates/user/show.html.twig
Labels: Reviewed by PO

#82 IsGranted assert for all our pages (excepted login)
  src/Controller/ResultPageController.php
  src/Controller/SimulatorController.php
Labels: Reviewed by PO

#80 S4 us8 password update
  assets/css/app.scss
  src/Controller/UserPasswordController.php
  src/Form/ChangePasswordType.php
  templates/base.html.twig
  templates/navbarProjetIO.html.twig
  templates/security/changePassword.html.twig
Labels: Reviewed by PO, conflict resolved

#92 Us21 update total acquisition
  src/Entity/Simulator.php
  src/Form/SimulatorType.php
  templates/Form/simulator.html.twig
  templates/resultTable.html.twig
Labels: Correction done, Reviewed by PO

#98 S5 us12 decoupage form
  assets/js/apiAdressRequest.js
  src/Controller/ResultPageController.php
  src/Controller/SimulatorController.php
  src/Entity/Finance.php
  src/Form/FinanceType.php
  src/Repository/FinanceRepository.php
  templates/Form/finance.html.twig
  templates/navbarProjetIO.html.twig
Labels: Correction done, Reviewed by PO

#97 US3_PANNEAU_ADMINISTRATEUR
  src/Controller/UserController.php
  src/Form/RegisterType.php
  templates/layoutAdmin.html.twig
  templates/user/_form.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: Correction done, Reviewed by PO

#94 Sprint5 us12 part1
  src/Controller/CivilStatusController.php
  src/Controller/TaxationController.php
  src/Entity/CivilStatus.php
  src/Entity/Simulator.php
  src/Entity/Taxation.php
  src/Form/CivilStatusType.php
  src/Form/SimulatorType.php
  src/Form/TaxationType.php
  src/Security/AppAuthenticator.php
  templates/Form/civilStatus.html.twig
  templates/Form/simulator.html.twig
  templates/Form/taxation.html.twig
  templates/navbarApplication.html.twig
  templates/navbarProjetIO.html.twig
Labels: Reviewed by PO, conflict resolved
