Repository WildCodeSchool/orleans-0918-php-loipinel, pull requests merged in 2019-01, with the labels that each got.

#104 fix apache
  composer.json
  composer.lock
  public/.htaccess
  symfony.lock
Labels: Reviewed by PO

#105 Fix dev
  assets/js/requestArea.js
  src/Controller/ResultPageController.php
  src/Entity/Taxation.php
  templates/Form/finance.html.twig
  templates/resultTable.html.twig
Labels: Correction done, Reviewed by PO

#96 Dev to Master
  assets/js/apiAdressRequest.js
  assets/js/requestArea.js
  composer.json
  composer.lock
  public/.htaccess
  src/Controller/CivilStatusController.php
  src/Controller/ResultPageController.php
  src/Controller/SimulatorController.php
  src/Controller/TaxationController.php
  src/Controller/UserController.php
  src/Entity/CivilStatus.php
  src/Entity/Finance.php
  src/Entity/Simulator.php
  src/Entity/Taxation.php
  src/Form/CivilStatusType.php
  src/Form/FinanceType.php
  src/Form/RegisterType.php
  src/Form/TaxationType.php
  src/Repository/FinanceRepository.php
  src/Security/AppAuthenticator.php
  symfony.lock
  templates/Form/civilStatus.html.twig
  templates/Form/finance.html.twig
  templates/Form/taxation.html.twig
  templates/layoutAdmin.html.twig
  templates/navbarApplication.html.twig
  templates/navbarProjetIO.html.twig
  templates/resultTable.html.twig
  templates/user/_form.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/user/show.html.twig
Labels: Reviewed by PO

#102 affiche ville page résultat ok
  composer.json
  composer.lock
  src/Controller/SimulatorController.php
  src/Service/ApiAddressRequest.php
  symfony.lock
Labels: Correction done, Reviewed by PO

#107 Sprint6 us11
  assets/css/app.scss
  assets/js/requestArea.js
  src/Form/FinanceType.php
  templates/Form/finance.html.twig
  templates/popup.html.twig
Labels: Correction done, Reviewed by PO

#106 Fix dev2
  src/Entity/Finance.php
  src/Entity/Taxation.php
  src/Form/FinanceType.php
  src/Form/TaxationType.php
  templates/Form/finance.html.twig
Labels: Correction done, Reviewed by PO

#114 Dev to Master 1
  assets/css/app.scss
  assets/js/requestArea.js
  composer.json
  composer.lock
  src/Controller/SimulatorController.php
  src/Entity/Finance.php
  src/Entity/Taxation.php
  src/Form/FinanceType.php
  src/Form/TaxationType.php
  src/Service/ApiAddressRequest.php
  symfony.lock
  templates/Form/finance.html.twig
  templates/popup.html.twig
Labels: Reviewed by PO

#116 correction suite à un problème api avec la ville de Boissettes
  composer.json
  src/Controller/SimulatorController.php
  src/Service/ApiAddressRequest.php
Labels: Reviewed by PO

#126 Us30 fix role
  composer.json
  src/Controller/SimulatorController.php
  src/Entity/User.php
  src/Service/ApiAddressRequest.php
  templates/user/index.html.twig
  templates/user/show.html.twig
Labels: Correction done, Reviewed by PO

#127 Us32 fix nom prenom membre
  templates/user/show.html.twig
Labels: Reviewed by PO

#136 Us5 variable update
  assets/css/app.scss
  src/Controller/VariableController.php
  src/Entity/Variable.php
  src/Form/VariableType.php
  src/Migrations/Version20190107104238.php
  src/Repository/VariableRepository.php
  src/Service/TaxBenefit.php
  templates/navbarApplication.html.twig
  templates/variable/_form.html.twig
  templates/variable/edit.html.twig
  templates/variable/index.html.twig
Labels: Reviewed by PO

#135 Dev to Master n°1 du Sprint 7
  assets/css/app.scss
  src/Controller/VariableController.php
  src/Entity/User.php
  src/Entity/Variable.php
  src/Form/RegisterType.php
  src/Form/VariableType.php
  src/Migrations/Version20190107104238.php
  src/Repository/VariableRepository.php
  src/Service/TaxBenefit.php
  templates/navbarApplication.html.twig
  templates/user/index.html.twig
  templates/user/show.html.twig
  templates/variable/_form.html.twig
  templates/variable/edit.html.twig
  templates/variable/index.html.twig
Labels: Reviewed by PO

#142 Fix pdf prod
  webpack.config.js
Labels: Reviewed by PO

#143 Us33 implémentation update user
  src/Controller/UserController.php
  src/Form/UserType.php
Labels: Reviewed by PO

#150 fix title
  templates/base.html.twig
Labels: Reviewed by PO

#151 Fix pour le style résultat
  templates/resultTable.html.twig
Labels: Reviewed by PO

#148 Dev to Master 2 du Sprint 7
  assets/css/app.scss
  src/Controller/UserController.php
  src/Form/UserType.php
  src/Migrations/Version20190107110609.php
  templates/base.html.twig
  templates/result.html.twig
  templates/resultTable.html.twig
  webpack.config.js
Labels: Reviewed by PO

#152 Fix style
  assets/css/app.scss
  src/Form/VariableType.php
  templates/variable/edit.html.twig
  templates/variable/index.html.twig
Labels: Correction done, Reviewed by PO

#153 Zone page result
  src/Controller/ResultPageController.php
  src/Controller/SimulatorController.php
  src/Service/ApiAddressRequest.php
  src/Service/DataJson.php
  src/Service/DataPinelJson.php
  templates/resultTable.html.twig
Labels: Reviewed by PO

#155 Reinitialisation password admin
  src/Controller/UserPasswordController.php
  src/Form/ChangePasswordType.php
  src/Form/UserType.php
  templates/security/resetPassword.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
Labels: Correction done, Reviewed by PO

#158 frontFix
  templates/navbarApplication.html.twig
  templates/navbarProjetIO.html.twig
Labels: Reviewed by PO

#141 Sprint7 us25
  assets/css/app.scss
  composer.json
  composer.lock
  src/Controller/CivilStatusController.php
  src/Controller/SimulatorController.php
  src/Controller/TaxationController.php
  templates/Form/civilStatus.html.twig
  templates/Form/finance.html.twig
  templates/Form/taxation.html.twig
  templates/navBarForm.html.twig
  templates/result.html.twig
Labels: Correction done, Reviewed by PO

#159 protecting simulator from login bypass with a GET request
  config/packages/security.yaml
  src/Controller/CivilStatusController.php
  src/Controller/TaxationController.php
  src/Controller/VariableController.php
Labels: Correction done, Reviewed by PO

#156 Dev to Master Sprint 7
  assets/css/app.scss
  composer.json
  composer.lock
  config/packages/security.yaml
  src/Controller/CivilStatusController.php
  src/Controller/ResultPageController.php
  src/Controller/SimulatorController.php
  src/Controller/TaxationController.php
  src/Controller/UserPasswordController.php
  src/Controller/VariableController.php
  src/Form/ChangePasswordType.php
  src/Form/UserType.php
  src/Form/VariableType.php
  src/Service/ApiAddressRequest.php
  src/Service/DataJson.php
  src/Service/DataPinelJson.php
  templates/Form/civilStatus.html.twig
  templates/Form/finance.html.twig
  templates/Form/taxation.html.twig
  templates/navBarForm.html.twig
  templates/navbarApplication.html.twig
  templates/navbarProjetIO.html.twig
  templates/result.html.twig
  templates/resultTable.html.twig
  templates/security/resetPassword.html.twig
  templates/user/_delete_form.html.twig
  templates/user/_form.html.twig
  templates/user/edit.html.twig
  templates/user/index.html.twig
  templates/user/new.html.twig
  templates/variable/edit.html.twig
  templates/variable/index.html.twig
Labels: Reviewed by PO

#160 Fix front
  templates/result.html.twig
Labels: Reviewed by PO

#161 Fix vue resultat
  templates/resultTable.html.twig
Labels: Reviewed by PO

#162 Fix prod
  composer.json
  composer.lock
Labels: Reviewed by PO

#164 Récupération adresse formulaire client avec requete api adresse
  assets/js/apiAdressCustomer.js
  src/Form/CivilStatusType.php
  templates/Form/civilStatus.html.twig
  webpack.config.js
Labels: Reviewed by PO

#166 Fix vue container
  templates/resultTable.html.twig
Labels: Reviewed by PO

#168 Fix front
  templates/navbarProjetIO.html.twig
Labels: Correction done, Reviewed by PO

#169 Fix service api adress request
  src/Service/ApiAddressRequest.php
Labels: Reviewed by PO

#170 modif apiadress js + finance template
  assets/js/apiAdressRequest.js
  templates/Form/finance.html.twig
Labels: Reviewed by PO

#171 Dev to Master Sprint 7 Jour 3
  assets/js/apiAdressRequest.js
  src/Service/ApiAddressRequest.php
  templates/Form/finance.html.twig
  templates/navbarProjetIO.html.twig
  templates/resultTable.html.twig
Labels: Reviewed by PO

#180 Fix reload ville
  assets/js/apiAdressCustomer.js
  templates/Form/civilStatus.html.twig
Labels: Reviewed by PO

#182 Asserts on user
  src/Entity/User.php
Labels: Correction done, Reviewed by PO

#183 Fix style resultat
  assets/css/app.scss
  templates/result.html.twig
  templates/resultTable.html.twig
  templates/resume.html.twig
Labels: Correction done, Reviewed by PO

#184 user.granted to user.roles
  templates/user/index.html.twig
  templates/user/show.html.twig
Labels: Reviewed by PO

#185 fix role display in user edit by admin
  templates/user/index.html.twig
  templates/user/show.html.twig
Labels: Reviewed by PO

#179 Us20 table amortissement pinel
  src/Controller/ResultPageController.php
  src/Migrations/Version20190110134305.php
  src/Service/TaxBenefit.php
  templates/resultTable.html.twig
  tests/TaxBaseTest.php
Labels: Correction done, Reviewed by PO

#187 bug de l'affichage des villes sur les formulaires / session fixé
  src/Entity/CivilStatus.php
  src/Entity/Finance.php
Labels: Reviewed by PO

#190 deleting ORM on finance entity
  src/Entity/Finance.php
  src/Migrations/Version20190111084654.php
Labels: Correction done

#197 Fix add user
  src/Entity/User.php
Labels: Reviewed by PO

#198 Fix edit user
  src/Entity/User.php
Labels: Reviewed by PO

#199 favicon
  assets/images/favicon.ico
  assets/js/app.js
  templates/base.html.twig
Labels: Correction done

#200 messages erreurs corrigés
  src/Entity/Finance.php
  src/Entity/Taxation.php
Labels: Reviewed by PO

#202 Fermeture des asserts
  src/Entity/Finance.php
  src/Entity/Taxation.php
Labels: Reviewed by PO

#196 correctif de la vue résultat pour une zone C
  src/Controller/ResultPageController.php
  src/Service/TaxBenefit.php
  templates/resultTable.html.twig
Labels: Correction done, Reviewed by PO

#201 Dev to master à passer après les PR
  assets/images/favicon.ico
  assets/js/app.js
  src/Controller/ResultPageController.php
  src/Entity/Finance.php
  src/Entity/Taxation.php
  src/Entity/User.php
  src/Service/TaxBenefit.php
  templates/base.html.twig
  templates/resultTable.html.twig
Labels: Reviewed by PO

#203 Fix_Master pour l'export pdf
  src/Controller/ResultPageController.php
Labels: Reviewed by PO

#204 Dev to MasterEnd Sprint
  src/Controller/ResultPageController.php
Labels: Reviewed by PO

#205 Indication de déplacement dans la navbar admin
  assets/css/app.scss
  templates/navbarApplication.html.twig
  templates/resultTable.html.twig
Labels: Reviewed by PO

#210 Fix_Message_User_Inexistant
  src/Security/AppAuthenticator.php
Labels: Reviewed by PO

#213 Dev to Master FixMaster
  assets/css/app.scss
  src/Controller/UserController.php
  src/Entity/User.php
  src/Form/ChangePasswordType.php
  src/Security/AppAuthenticator.php
  templates/navbarApplication.html.twig
  templates/resultTable.html.twig
  templates/user/edit.html.twig
Labels: Reviewed by PO

#217 Changement du peut en doit dans le message d'erreurs
  src/Form/FinanceType.php
  src/Form/TaxationType.php
Labels: Reviewed by PO

#218 deleting useless method who can be used by a get request
  src/Controller/UserController.php
  templates/user/show.html.twig
Labels: Reviewed by PO

#221 Upload json file
  config/services.yaml
  pinel.json
  src/Controller/VariableController.php
  src/Entity/UploadJson.php
  src/Entity/Variable.php
  src/Form/JsonFileType.php
  templates/variable/index.html.twig
Labels: Correction done, Reviewed by PO

#223 assert corrigé
  Data/pinel.json
  src/Entity/UploadJson.php
Labels: Reviewed by PO

#224 Dev to master upload json
  config/services.yaml
  pinel.json
  src/Controller/VariableController.php
  src/Entity/UploadJson.php
  src/Entity/Variable.php
  src/Form/JsonFileType.php
  templates/variable/index.html.twig
Labels: Reviewed by PO
